### ISSUE TITLE
fix(Contributing): Fix glaring mistakes in contribution guide

### ISSUE THREAD

**Issue by KyomiDev** [PenPow/SignalBot#13]
**Describe the bug**
In the [Contributing Guide](https://github.com/PenPow/SignalBot/blob/d9fb3483dc44c7d4ae93c88c1adb0e203391b4bc/.github/CONTRIBUTING.MD), it slipped by me but we need to fix the issues regarding the typescript code + npm install code, as we use yarn for the project. 🤦‍♂️

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [The Contributing Guide](https://github.com/PenPow/SignalBot/blob/d9fb3483dc44c7d4ae93c88c1adb0e203391b4bc/.github/CONTRIBUTING.MD)
4. Read the Steps

**Expected behaviour**
It shows _correct steps_ to help contribute.

**Comment by PenPow** [comment]
Note to self, always read through the docs you yoink from another one of your projects.

Ill let you write the PR for this while I work on #12
