### ISSUE TITLE
refactor(functions): Combine Functions for Messages and Slash Commands

### ISSUE THREAD

**Issue by PenPow** [PenPow/SignalBot#39]
**Is your feature request related to a problem? Please describe.**
Having multiple functions makes the code hard to maintain, a solution would be to replace the functions with bigger ones that can handle both commands and slash commands, with only one section to change rather than two.

**Describe the solution you'd like**
As a developer, I would like to have a single function which attempts to handle both regular commands and slash commands.

**Describe alternatives you've considered**
Pushing #37 forward for Signal V2 and scrapping this idea.

**Comment by KyomiDev** [comment]
Was too lazy to make a PR for this, but implemented in the latest function.

Also I decided not to replace the slashrun function for ease of clarity, and considering the fact that we plan on removing it next major release anyway
